"""The committed embedding coupling cache (fixtures/coupling_cache_embedding) was
generated by the ET 0.4.3-era juliacall shim, and the embedding tests re-stamp it
under the current backend id.  This pins that those entries are still the
current backend's couplings up to the per-B-row scale ET main introduced: same
A-basis, same AA columns, same nnll rows, each B row a nonzero multiple of the
recomputed one (degenerate blocks: same row space).  Needs the compiled library."""
import json
import pathlib

import numpy as np
import pytest

from conftest import require_coupling_lib

FIX = pathlib.Path(__file__).resolve().parents[1] / "fixtures" / "coupling_cache_embedding"
ENTRIES = sorted(FIX.glob("cpl-*.npz"))


def _load(path):
    z = np.load(path)
    m = json.loads(bytes(z["meta_json"]).decode())
    mb = [[tuple(b) for b in bb] for bb in m["mb"]]
    return (mb, [tuple(r) for r in m["rnl"]], [tuple(y) for y in m["ylm"]],
            np.asarray(z["A2B"]), [tuple(tuple(t) for t in s) for s in m["aa_sig"]],
            [tuple(r) for r in m["aspec"]], [tuple(tuple(b) for b in bb) for bb in m["nnll_spec"]])


@pytest.mark.parametrize("path", ENTRIES, ids=[p.name for p in ENTRIES])
def test_committed_entry_matches_backend_up_to_row_scale(path):
    require_coupling_lib()
    from ace_jax.construct.coupling import couple, subspace_residual
    mb, rnl, ylm, A_old, sig_old, aspec_old, nnll_old = _load(path)
    cpl = couple(mb, rnl, ylm)
    assert [tuple(r) for r in cpl.aspec] == aspec_old
    assert [tuple(r) for r in cpl.nnll_spec] == nnll_old            # same B rows, same order
    key = lambda s: tuple(sorted(s))
    col = {key(s): j for j, s in enumerate(sig_old)}
    assert len(col) == len(sig_old) and sorted(map(key, cpl.aa_sig)) == sorted(col)
    A_old = A_old[:, [col[key(s)] for s in cpl.aa_sig]]              # old columns in new order
    A_new = np.asarray(cpl.A2B)
    assert A_new.shape == A_old.shape
    blocks = {}
    for b, bb in enumerate(nnll_old):
        blocks.setdefault(tuple(sorted(bb)), []).append(b)
    worst = 0.0
    for rows in blocks.values():
        cols = np.flatnonzero(np.abs(A_old[rows]).sum(0) + np.abs(A_new[rows]).sum(0))
        P, Q = A_new[np.ix_(rows, cols)], A_old[np.ix_(rows, cols)]
        if len(rows) == 1:
            s = float((P * Q).sum() / (Q * Q).sum())
            assert s != 0.0
            worst = max(worst, float(np.abs(P - s * Q).max() / np.abs(P).max()))
        else:
            worst = max(worst, subspace_residual(P, Q))
    assert worst < 1e-12, worst
